### ISSUE TITLE
Dominance Finder Out of Bounds Error

### ISSUE THREAD

**Issue by will-leeson** [soot-oss/SootUp#586]
When I attempt to build a DominanceFinder object, I am getting an Array Out of Bounds Exception:

Here is the snippet of my code which produces the error:
```java
for(JavaSootMethod aMethod : aClass.getMethods()){ 
    if(aMethod.hasBody()){
        StmtGraph<?> graph = aMethod.getBody().getStmtGraph();
        df = new DominanceFinder(graph);
        ...
```

Here is the stack trace:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 18
	at sootup.core.graph.DominanceFinder.getFirstDefinedBlockPredIdx(DominanceFinder.java:167)
	at sootup.core.graph.DominanceFinder.<init>(DominanceFinder.java:75)
	at com.lesslab.ProgramGraph.GraphBuilder.buildGraphs(GraphBuilder.java:193)
	at com.lesslab.ProgramGraph.App.main(App.java:45)
```

**Comment by will-leeson** [comment]
In case this is helpful, I did a bit of digging and found that about 50% of the time (on the fairly large system I'm testing), the out of bounds error is equal to the size of the number of basic blocks. The other 50% of the time the out of bounds error has a message of null. 

This smells like a off by one error to me

**Comment by fberlakovich** [comment]
I just ran into the same error. The reason is that the comparison at https://github.com/soot-oss/SootUp/blob/f5bc428948b27b107f90b62eae6d102dd9eaeba0/sootup.core/src/main/java/sootup/core/graph/DominanceFinder.java#L48 is incorrect. The comparison reference compares two `ForwardingBlock`s , which are not the same object reference. Only their backing blocks are the same object reference.
