### ISSUE TITLE
Bytecodefrontend creates a dead assignment in traphandler code - investigate (and fix?)

### ISSUE THREAD

**Issue by swissiety** [soot-oss/SootUp#792]
compiled source of
```java
	public void doGet(HttpServletRequest request) {
		String userId = request.getParameter("userId");
		String alias = userId;
		try {
			Connection conn = DriverManager.getConnection("url", "userName", "password");
			Statement st = conn.createStatement();
			String query = "SELECT * FROM  User where userId='" + alias + "'";
			st.executeQuery(query);
		} catch (Exception e) {
			System.out.println("Something went wrong");
		}
		System.out.println(userId);
		System.out.println(alias);
	}
```

generates

```
  label3:
    $stack13 := @caughtexception;
    $conn = $stack13;                          // <--- here
    $stack14 = <java.lang.System: java.io.PrintStream out>;
    virtualinvoke $stack14.<java.io.PrintStream: void println(java.lang.String)>("Something went wrong");
```

its never used again and interferes e.g. with typing as the Local is already used somewhere else (but not again - it just exists).

**Comment by Timbals** [comment]
This seems to be "correct" behavior.

Looking at the disassembled bytecode, the exception is actually stored into the same local variable as the user id.
I.e. there is an actual `astore 2` bytecode instruction in the exception handler.
Since both are just `reference`s from the point of the JVM, this is valid.

The exception might be used which means the dead assignment eliminator will not be able to eliminate this every time.

The LocalSplitter should fix this though.
Assuming the TypeAssigner is ran after the LocalSplitter this shouldn't cause any issues with typing.

The only potential problem I can see is if the names of variables are used in Jimple in the future (#780).

**Comment by swissiety** [comment]
Thanks for investigating that! regarding #780 Localsplitter will append as usual - keeping it as close to the original as possible.
