### ISSUE TITLE
fix TypeAssigner

### ISSUE THREAD

**Issue by swissiety** [soot-oss/SootUp#799]
1) lab3:fieldSQLInjection1 - it does not type precisely - but creates casts for all further usages of $stack8

```
    $stack8 = new target.hidden.exercise2and3.FieldSQLInjection1$ObjectWithTaint;
```

2) does not type single defs - but casts them - so the information seems to be gathered

3) splits a single assignment into 2 varibles (maybe connected with 2) ?)

**Comment by Timbals** [comment]
Note on 2/3:
This is probably just the way your testcase was set up.
When a class `A` contains a `package x.y.z;` statement at the top but isn't in directory `x/y/z` then the class signature will be a bit messed up.
Due to the code [here](https://github.com/soot-oss/SootUp/blob/36a96547431188cf6203adcf5570e37cfe5dc974/sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/PathBasedAnalysisInputLocation.java#L193) that means the `this` variable will be typed as `A` (with an empty package name) but its methods will be typed as `x.y.z.A#method` which causes the unnecessary casts.
