### ISSUE TITLE
remove $stack for object initialization 

### ISSUE THREAD

**Issue by Liyw979** [soot-oss/SootUp#838]
java code
```
import java.util.*;
class Test1{
    public static void main(String[] args){
        List<Integer> nums = new ArrayList();
    }
}
```
jimple code
```
{
    java.lang.String[] l0;
    unknown $stack2, l1;


    l0 := @parameter0: java.lang.String[];
    $stack2 = new java.util.ArrayList;
    specialinvoke $stack2.<java.util.ArrayList: void <init>()>();
    l1 = $stack2;

    return;
}
```
expected, looks better
```
    nums = new java.util.ArrayList;
    specialinvoke nums.<java.util.ArrayList: void <init>()>();
    return;

```

**Comment by swissiety** [comment]
What is your intention in this Issue? Is it a question how to get the expected result, a suggestion to improve or even a bug report? 
Please add more information/context - e.g. your sootup setup - so that we can understand the context and don't have to guess.

e.g. needed context would be: 
- did your bytecode contain debug information like: local names? To be able to infer the name.
- which BodyInterceptors were enabled? (btw. the `BodyInterceptor` Aggregator would/should help generate the expected output)
