### ISSUE TITLE
Unhandled ResolveExceptions during CHA initialize: Method Dispatch Resolution Issue

### ISSUE THREAD

**Issue by Westwood-Lin** [soot-oss/SootUp#870]
Hello SootUp team, I am using SootUp for my research. So, before describing the issue, let me say **thank you** first ❤️
I'm still learning the ropes and may have missed some of the guides, issues, and code branches. As a result, I might have repeated questions or feedback that has already been covered.
I'm fairly new to GitHub and may not always be the best at expressing my ideas. I apologize if my communication isn't as clear as it could be.

- Background
- Brief
- Related Test

# Background
SootUp version: 1.1.2
Installation: maven
Analysis object: an apk file of a commercial Android application, an Android library (jar file), and the jdk8 jar file.
How SootUp is used:  I used the CHA algorithm to construct the method call relationships among these analysis objects (i.e., to build call graphs).

# Brief
Use ' **A -> B**' represents **method A invokes method B**;

1. ClassHierarchyAnalysisAlgorithm: resolveCall(...) -> resolveAllSubClassCallTargets(...) -> MethodDispatchResolver: resolveConcreteDispatch().

The method MethodDispatchResolver: **resolveConcreteDispatch() may throw an exception**. However, the invokers resolveAllSubClassCallTargets and resolveCall neither throw nor handle this exception with try-catch blocks. This directly leads to multiple abnormal terminations of my construction algorithm.

2. If a MethodSignature object in the Worklist (referred to as 'target') is <java.lang.StringBuilder: java.lang.AbstractStringBuilder append(char)>, known that the class StringBuilder inherits from AbstractStringBuilder, and there is an actual method inside StringBuilder: append(char). If we acknowledge the Liskov Substitution Principle, then the target to be analyzed can be regarded as actually implemented by <java.lang.StringBuilder: java.lang.StringBuilder append(char)>. However, in the current algorithm, this target is considered to have no corresponding actual method.

The issue may lies in this call chain:

MethodDispatchResolver: resolveConcreteDispatch(...) -> MethodDispatchResolver: findConcreteMethodInSootClass(...) -> `return ((MethodSubSignature)methodSignature.getSubSignature()).equals(((MethodSignature)potentialTarget.getSignature()).getSubSignature());` -> MethodSubSignature: equals().

In the method equals(...) of the MethodSubSignature class, equality is defined as: the same one object or (same method name && same return type && same parameter types).

When searching for the target, its declaring class 'StringBuilder', name 'append', and parameter '(char)' are all the same as the actual method <java.lang.StringBuilder: java.lang.StringBuilder append(char)>. 
**Only the return value is different, so equals returns false. And findConcreteMethodInSootClass will not link the actual method with the target object.**

Therefore, if we want the target object to point to the actual StringBuilder: append(...) method, it is best to modify the findConcreteMethodInSootClass() method. Using equals(...) directly doesn't seem particularly reasonable.

# Related Test
Based on my analysis, I also defined some following test cases.

```java
public static <List> void main(String[] args) {
        // init project
        String targetApkPath = "...";
        String androidJarPath = "...";
        String jdkPath = System.getProperty("java.home") + "/lib/rt.jar";
        JavaLanguage language = new JavaLanguage(8);
        JavaProject p = JavaProject.builder(language)
                .addInputLocation(new JavaClassPathAnalysisInputLocation(targetApkPath))
                .addInputLocation(new JavaClassPathAnalysisInputLocation(androidJarPath))
                .addInputLocation(new JavaClassPathAnalysisInputLocation(jdkPath)).build();
        JavaView view = (JavaView) p.createView(new LRUCacheProvider<JavaSootClass>(100));

	// Test1
       // Analyze <java.lang.StringBuilder: java.lang.StringBuilder append(char)>
    	// OK
	String declare1="java.lang.StringBuilder";
        String ret1="java.lang.StringBuilder";
        String method="append";
        ClassType str=view.getIdentifierFactory().getClassType("java.lang.String");
        ArrayList params =  new ArrayList<ClassType>();
        params.add(str);
        test(view,declare1,method,params,ret1);

        // Test2
    	// Analyze <java.lang.StringBuilder: java.lang.AbstractStringBuilder append(char)>
	// ResolveException: Could not find concrete method for <java.lang.StringBuilder: java.lang.AbstractStringBuilder append(char)> ./file-does-not-exist NoPositionInformation
	String ret2="java.lang.AbstractStringBuilder";
        test(view,declare1,method,params,ret2);

    	// Test3
    	// Analyze <java.time.chrono.HijrahDate: java.time.chrono.ChronoLocalDate plusYears(long)>
	// ResolveException: Could not find concrete method for <java.time.chrono.HijrahDate: java.time.chrono.ChronoLocalDate plusYears(long)>
        String declare3="java.time.chrono.HijrahDate";
        String ret3="java.time.chrono.ChronoLocalDate";
        String method3="java.time.chrono.ChronoLocalDate plusYears(long)";
        PrimitiveType.LongType.LongType param1 = PrimitiveType.getLong();
        ArrayList params3 =  new ArrayList<PrimitiveType>();
        params.add(param1);
        test(view,declare3,method3,params3,ret3); 
    
        logger.info("Test finish");
}
    public static void test(JavaView view, String declaringTypeString, String name, Iterable<Type> params , String retTypeString){
        ClassType classType = view.getIdentifierFactory().getClassType(declaringTypeString);;
        ClassType retType = view.getIdentifierFactory().getClassType(retTypeString);
        MethodSignature ms=new MethodSignature(classType, name ,params, retType);

        Optional<MethodSignature> methodSignature = MethodDispatchResolver.resolveConcreteDispatch(view, ms);

        if(methodSignature.isPresent())
            logger.info(methodSignature.get().toString() +" OK");
    }

```

**Comment by JonasKlauke** [comment]
Hello Westwood-Lin,
We have released version 1.2 which logs only warnings if the call graph algorithm reaches methods which are not defined in the input locations. Therefore it should not terminate anymore. We recommend to update to our newest version.
If I understand you right, you are talking about covariance in the second part, or?
That the return type can be a sub type of the actual return type. for example:
```
class A{
  A m(){....}
}
class B extends A{
  B m(){....}
}
```
In this example m of class B would override m of A because B is a subtype of A following the covariance rule.
This is correct on Sourcecode level, but on Bytecode level the compiler will generate a method A m(){...} in B that will call the other m method with the Subtype return value. 
Therefore the call graph will show an edge to the so called bridge method.

**Comment by Westwood-Lin** [comment]
Dear JonasKlauke,
Thank you for your prompt response. 
I've learned that version 1.2 addresses the first problem. 
Your explanation also clarified the concept of covariance for me in the second part.

Again, I sincerely appreciate your explanation in resolving my query.

**Comment by swissiety** [comment]
From what I understood from your desciption the problem is, 
1.1) that due to the difference in the returnType of `B B.m()` and the method in the super class `A A.m()` - its not considered because the check for As_returnType.equals(Bs_returnType) fails. 
So its proposed to do: A_returnType.isSuperClassOrEquals(B).

1.2) But as @JonasKlauke explained there is an additional call added in the bytecode via a bridge method which is `A B.m()` - this is considered because equals() is true in that case.

So from your description what should happen & @JonasKlauke added information this works as intended.


On the other hand the example test code seems inconsistent to the description?
(ignoring that the parameter is java.lang.String vs. char - its structurally equivalent)

2.1) `<java.lang.StringBuilder: java.lang.AbstractStringBuilder append(char)>` would be `A B.m()` in Jonas' example.
which from your code/comment is *not* considered, but from your&our explanation should be considered when compared with its method from the parent `A A.m()` (as methodname, returntype, parameters match).

So if that code/comment is correct something does not work as intended; please check the bytecode if the method exists - maybe its done differently in apk/dex and they don't use bridge methods so then we have to handle it differently?

2.2) from your code/comment: `<java.lang.StringBuilder: java.lang.StringBuilder append(char)>` is found - but as the returntype is not equal: it should not directly with `A A.m()` - but it can be called directly on its own - seems fine to me.


Example:
```java
public class A {
    A m() {
        System.out.println(1);
        return new A();
    }
}

class B extends A {
    B m() {
        System.out.println(2);
        return new B();
    }

    static void foo() {
        new A().m();
        new B().m();
        ((A) new B()).m();
    }
}
```

ByteCode of class B:
```
class B extends A {
  B();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method A."<init>":()V
       4: return

  B m();
    Code:
       0: getstatic     #7                  // Field java/lang/System.out:Ljava/io/PrintStream;
       3: iconst_2
       4: invokevirtual #13                 // Method java/io/PrintStream.println:(I)V
       7: new           #19                 // class B
      10: dup
      11: invokespecial #21                 // Method "<init>":()V
      14: areturn

  A m();
    Code:
       0: aload_0
       1: invokevirtual #26                 // Method m:()LB;
       4: areturn

  static void foo();         // To show the actual calls
    Code:
       0: new           #2                  // class A
       3: dup
       4: invokespecial #1                  // Method A."<init>":()V
       7: invokevirtual #22                 // Method A.m:()LA;
      10: pop
      11: new           #19                 // class B
      14: dup
      15: invokespecial #21                 // Method "<init>":()V
      18: invokevirtual #26                 // Method m:()LB;
      21: pop
      22: new           #19                 // class B
      25: dup
      26: invokespecial #21                 // Method "<init>":()V
      29: invokevirtual #22                 // Method A.m:()LA;
      32: pop
      33: return

}
```

**Comment by Westwood-Lin** [comment]
Dear swissiety,

Thank you sincerely for your detailed explanation. Your comment came just as I was about to close this issue. What an interesting coincidence! 🙂

I have read your response multiple times. The explanation in the second part was particularly insightful for me. I will carefully examine how bridge methods are handled in apk/dex files and investigate other potential causes of errors.
I'm planning to close this issue now.

Once again, thank you for your response.
